// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: 2026 konikvranik
//
// MDI icons from Home Assistant; the extension bundles the full SVG set
// (icons/mdi, generated by tools/fetch-mdi.py from @mdi/svg, Apache-2.0).
// SVGs have baked-in white fill - GNOME panel is dark and non-symbolic
// icons (Gio.FileIcon) cannot be dynamically recolored.
//
// Colored variants (light state) are baked at runtime: fill is overwritten
// and SVG is saved to user cache directory (~/.cache/hmass-mdi).
//
// Input name is the entity "icon" attribute, e.g. "mdi:water-pump".

import Gio from 'gi://Gio';
import GLib from 'gi://GLib';

const _cache = new Map();
let _dir = null;
let _dirResolved = false;
let _cacheDir = null;

export function setIconDir(dir) {
    _dir = dir;
    _dirResolved = true;
}

function _iconDir() {
    if (!_dirResolved) {
        _dirResolved = true;
        try {
            const extUtils = globalThis.imports?.misc?.extensionUtils;
            const Me = extUtils?.getCurrentExtension?.();
            if (Me && Me.dir)
                _dir = Me.dir.get_child('icons').get_child('mdi');
        } catch (e) {
        }
    }
    return _dir;
}

function _cacheDirFile() {
    if (_cacheDir === null) {
        _cacheDir = false;
        try {
            const d = Gio.file_new_for_path(GLib.get_user_cache_dir())
                .get_child('hmass-mdi');
            if (!d.query_exists(null))
                d.make_directory_with_parents(null);
            _cacheDir = d;
        } catch (e) {
            // cache cannot be written - colored variants return white
        }
    }
    return _cacheDir || null;
}

/**
 * Returns gicon for MDI name, or null (unknown/missing icon).
 * @param {string} mdiName e.g. "mdi:water-pump"
 * @param {string|null} fillHex e.g. "#FF8800" for colored variant
 *   (null = white base version from bundled set)
 */
export function mdiIcon(mdiName, fillHex) {
    if (!mdiName || mdiName.indexOf('mdi:') !== 0)
        return null;
    const name = mdiName.slice(4);
    const key = fillHex ? name + fillHex : name;
    if (_cache.has(key))
        return _cache.get(key);
    let gicon = null;
    const dir = _iconDir();
    if (dir) {
        if (fillHex && /^[0-9a-fA-F]{6}$/.test(fillHex.slice(1))) {
            try {
                const src = dir.get_child(name + '.svg');
                const [ok, bytes] = src.load_contents(null);
                if (ok) {
                    const svg = new TextDecoder().decode(bytes)
                        .replace('fill="#FFFFFF"', `fill="#${fillHex.slice(1)}"`);
                    const cd = _cacheDirFile();
                    if (svg.indexOf(fillHex) >= 0 && cd) {
                        const dst = cd.get_child(`${name}-${fillHex.slice(1)}.svg`);
                        dst.replace_contents(svg, null, false,
                            Gio.FileCreateFlags.REPLACE_DESTINATION, null);
                        gicon = Gio.FileIcon.new(dst);
                    }
                }
            } catch (e) {
                // coloring failed - base white version will be used
                gicon = null;
            }
        }
        if (!gicon) {
            const file = dir.get_child(name + '.svg');
            if (file.query_exists(null)) {
                gicon = Gio.FileIcon.new(file);
            } else {
                log(`hmass: mdi icon not found in set: ${name}`);
            }
        }
    }
    _cache.set(key, gicon);
    return gicon;
}

/** Checks whether icon exists in bundled set (diagnostics/tests). */
export function hasMdi(mdiName) {
    return mdiIcon(mdiName) !== null;
}
